### ISSUE TITLE
specifying input number style

### ISSUE THREAD

**Issue by back5576** [jehugaleahsa/FlatFiles#15]
I didn't see anything in the tests, so I'm not sure if is possible or if so how to use it. I have in my csv strings like
12,345.67
and
$34.12

I'm curious if FlatFiles can parse these with a specified input formatter

**Comment by jehugaleahsa** [comment]
If you're working directly with schemas, the numeric columns types provide
NumberStyle properties:
https://github.com/jehugaleahsa/FlatFiles/blob/master/src/FlatFiles/DecimalColumn.cs#L38.
If you're using type mappers, you can use the NumberStyles method:
https://github.com/jehugaleahsa/FlatFiles/blob/master/src/FlatFiles/TypeMapping/DecimalPropertyMapping.cs#L31.


Let me know if I misunderstood your question.

**Comment by back5576** [comment]
I had tried that - using this syntax:

mapper.Property(p => p.Cost).NumberStyles(NumberStyles.Number);

but get a compile error:

"The name 'NumberStyles' does not exist in the current context"

**Comment by back5576** [comment]
Ah - never mind. I had left out

using System.Globalization;
