### ISSUE TITLE
Type Mappers with fixed length fields?

### ISSUE THREAD

**Issue by back5576** [jehugaleahsa/FlatFiles#17]
Does the Type Mappers pattern support fixed length fields? If so, where does one put the field length?

**Comment by jehugaleahsa** [comment]
Yeah. Take a look at the `FixedLengthTypeMapper` class (https://github.com/jehugaleahsa/FlatFiles/blob/master/src/FlatFiles/TypeMapping/FixedLengthTypeMapper.cs#L46). You'll see it provides the same `Property` methods,  accepting a `Window` object. A `Window` defines the length of the field and other options. If all you care about is the length, you can just pass the length to the `Property` method and it will get convertered to a `Window` implicitly. E.g.:

    var mapper = FixedLengthTypeMapper.Define<Blah>();
    mapper.Property(x => x.Field, 10);
