### ISSUE TITLE
FlatFiles does not support uint or short

### ISSUE THREAD

**Issue by silkfire** [jehugaleahsa/FlatFiles#18]
It looks like FlatFiles currently doesn't support mapping to `uint` or `short`, I need to change my types to `int` or I'm getting exceptions (something with Property not selected).

**Comment by jehugaleahsa** [comment]
Is this specific to type mappers? It's true there's no support for unsigned
types, but there is mapping support for Int16 (short). Any more detail you
can provide would be great.

**Comment by silkfire** [comment]
Yes I'm using type mappers exclusively, I find them actually very clean and streamlined.

`_flatFileTypeMapper.Property(sr => sr.Value, new Window(7) { Alignment = FixedAlignment.RightAligned });`

If the `Value` property is defined as a `uint`, I'm getting an exception.

**Comment by jehugaleahsa** [comment]
Behind the scenes .NET is casting the uint to long, which is being captured
in the expression tree. Unfortunately, that cast prevents FlatFiles from
correctly identifying the Value property.

Tomorrow, I'll look into adding unsigned support. Should be a trivial
change. It's surprising it's not come up before.

**Comment by silkfire** [comment]
Thank you. Looking forward to the update.

**Comment by jehugaleahsa** [comment]
As soon as NuGet refreshes, you should see a 0.3.20.0 version. I added support for sbyte, uint16, uint32 and uint64. Let me know if you encounter any issues.
