### ISSUE TITLE
Handling Null Values for Booleans

### ISSUE THREAD

**Issue by kjmoon** [jehugaleahsa/FlatFiles#20]
I don't think the Boolean type mapping property can handle nulls :( 

The BooleanColumn parse method will return a null, and when it tries to cast that there is a cast exception.

Shouldn't the default for Null be False?

**Comment by jehugaleahsa** [comment]
I just created 6 new unit tests, 3 for CSV and 3 for fixed-length files. They test round-tripping (reading/writing) `boolean?` with `true`, `false` and `null`. Could you provide more details or some sample code illustrating the issue?

**Comment by kjmoon** [comment]
Thanks! Sorry I'm sure there are other bugs in my code that is causing strange null reference exceptions.

My question is that, if I'm using a TypeMapper that maps a column to a bool or int type, and the reader encounters an "N/A", which I've mapped to a NullValue, then does the parser use a default value of false or 0 for non-nullable types?

**Comment by jehugaleahsa** [comment]
Ah, I see. The parser will return null, not zero. So when the type mapper
goes to convert it to a non-nullable type it fails to cast.

It might make more sense to make the property nullable and then when you
refer to that property, use the null coalesce operator, e.g., `a.IsActive
?? false`.

Thanks,
Travis
