### ISSUE TITLE
DataRecordExtensions.GetNullableString(this IDataRecord record, int i) is recursive

### ISSUE THREAD

**Issue by pbolduc** [jehugaleahsa/FlatFiles#33]
This function looks to be a recursive call with no exit. Calling it would throw StackOverflowException.

https://github.com/jehugaleahsa/FlatFiles/blob/0086bae78d29139e1063b4c915c383121e96e12f/FlatFiles/DataRecordExtensions.cs#L628-L631

**Comment by jehugaleahsa** [comment]
Thanks for the heads up. I added some additional tests and pushed 3.0.1.
