### ISSUE TITLE
DataTable WriteFlatFile extension method can't handle DBNull

### ISSUE THREAD

**Issue by ckarras** [jehugaleahsa/FlatFiles#40]
**Describe the bug**
I have a DataTable with nullable columns and I'm trying to export it to CSV format using the WriteFlatFile extension method. When a value is null, it is represented as DBNull.Value. This causes an exception:

`InvalidCastException:` Unable to cast object of type 'System.DBNull' to type 'System.String'.

**To Reproduce**
```csharp
using System;
using System.Data;
using System.IO;
using FlatFiles;

namespace ReproduceFlatFilesDBNullBug
{
    class Program
    {
        static void Main(string[] args)
        {
            // create DataTable with 1 row and DBNull value
            DataTable dt = new DataTable();
            dt.Columns.Add("Test", typeof(string));
            
            dt.Rows.Add(dt.NewRow());
            dt.Rows[0]["Test"] = DBNull.Value;

            // try to write as CSV using FlatFiles WriteFlatFile extension method on DataTable
            SeparatedValueSchema schema = new SeparatedValueSchema();
            schema.AddColumn(new StringColumn("Test") { IsNullable = true });

            using (var destinationWriter = new StringWriter())
            {
                var csvWriter = new SeparatedValueWriter(destinationWriter, schema);
                dt.WriteFlatFile(csvWriter);
                Console.WriteLine(destinationWriter.ToString());
            }
        }
    }
}
```

**Expected behavior**
Null strings should be represented as a blank value in the CSV file (this shouldn't throw an exception)

**Screenshots**
N/A

**Version:**
FlatFiles 4.3.0

**Additional context**

Detailed stack trace:
```
FlatFiles.RecordProcessingException
  HResult=0x80131500
  Message=Encountered an invalid conversion while processing the record. Record 0.
  Source=FlatFiles
  StackTrace:
   at FlatFiles.SeparatedValueWriter.ProcessError(RecordProcessingException exception)
   at FlatFiles.SeparatedValueWriter.Write(Object[] values)
   at FlatFiles.DataTableExtensions.WriteFlatFile(DataTable table, IWriter writer)
   at ReproduceFlatFilesDBNullBug.Program.Main(String[] args) in ReproduceFlatFilesBug\Program.cs:line 26

Inner Exception 1:
ColumnProcessingException: Failed to convert '' to 'System.String'. Column: Test, Position: 0.

Inner Exception 2:
InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
```

As a workaround, I created a "DbNullableStringColumn" class that decorates a StringColumns and converts DBNull to/from null. However, this probably doesn't follow the intended design:  I see from this commit's comment that nulls should be handled directly on column classes: https://github.com/jehugaleahsa/FlatFiles/commit/9ed01f7e4494569a45da27a289167810c3f4c9e9

**Comment by jehugaleahsa** [comment]
You're right. That should just work the way you'd expect it to. That should be an easy change. I'll let you know when it's available.

**Comment by jehugaleahsa** [comment]
Okay, I have pushed version 4.3.1 to NuGet. Please let me know if you have any concerns.
