### ISSUE TITLE
How to add the auto generated RecordNumberCoulmn in FixedLengthSchema for the reader?

### ISSUE THREAD

**Issue by gituseryt** [jehugaleahsa/FlatFiles#42]
Could you please let me know how to set the Window parameter for adding the auto generated RecordNumberCoulmn in FixedLengthSchema:
           var schema = new FixedLengthSchema()
                    .AddColumn(new RecordNumberColumn("RecordNumber"),?)

**Comment by pbolduc** [comment]
Hi Travis, I work with the OP regarding this issue.  We are using your library to import CSV and flat files into the a database via IDataReader and SqlBulkCopy. Our common code uses the schema / reader for the bulk copy.  The API surface does not appear to have a way to use the metadata column with FixedLengthSchema.  The tests show usage using meta data but using the RecordNumberColumn directly with FixedLengthSchema.

**Comment by jehugaleahsa** [comment]
Why can't you just add the column to the schema with a column length of 10
or something? Like I said,  I don't think the length matters. Let me know
otherwise.

**Comment by pbolduc** [comment]
Would you expect something like this to work?

```cs
[TestMethod]
public void TestFixedLengthSchema_Without_Mapper()
{
  string output = @"30header
31detail
39footer
";
  var stringReader = new StringReader(output);

  var schema = new FixedLengthSchema()
    .AddColumn(new RecordNumberColumn("RecordNumber"), 10)
    .AddColumn(new Int16Column("RecordType"), 2)
    .AddColumn(new StringColumn("Data"), 6);

  var reader = new FixedLengthReader(stringReader, schema);

  Assert.IsTrue(reader.Read(), "The header record could not be read.");

  var data = reader.GetValues();

  Assert.IsNotNull(data);
}```

When I run this, reader.Read() function never returns.  When I call FixedLengthSchema.AddColumn and the column is a metadata column, it would expect that the reader does not advance.  It seems like there should be an overload for a MetadataColumn that does not expect a width/window.

**Comment by jehugaleahsa** [comment]
Thanks for going through the trouble of writing a unit test. I added it to my code base: https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles.Test/FixedLengthReaderMetadataTester.cs#L367. It made it easy to identify what the issue was. You should be seeing a new v4.3.3 NuGet package with the fix applied soon. Thanks again!

**Comment by jehugaleahsa** [comment]
As a side note, I've thought about the fact that you have to provide a column width unnecessarily. In fact, there are several places in the library where you must (or can) provide additional information even if it is never used. I had thought about splitting out the interfaces for "read-only" vs "write-only" vs "read-write". Most of the time you are doing one or the other but not both. For now, I've decided the inconvenience isn't worth addressing. Certainly something to keep on the back burner, though. Thanks for the suggestion, though.
