### ISSUE TITLE
Comment character

### ISSUE THREAD

**Issue by rgarrison12345** [jehugaleahsa/FlatFiles#48]
I know that there is no official standard for a delimited file/fixed width beyond a RFC.  I know that there is no official standard regarding comment lines in CSV/fixed width files, but people do use it at least in a de facto standard sense.  Can there be an ability to skip/write comment lines in a CSV/fixed width file?  The most common comment character to signify a line is a comment is the # sign.  Other text files do this as well like the host file on windows just as an example.

**Comment by jehugaleahsa** [comment]
The way you handle this in FlatFiles is to register with the `RecordRead` on the `SeparatedValueReader` class. Then on the `SeparatedValueRecordReadEventArgs` class, set the `IsSkipped` property to `true` if `Values.Length > 0 && Values[0].startsWith("#")`.

**Comment by jehugaleahsa** [comment]
As for writing out comments, I am tempted to just add the ability to write arbitrary text... like adding `WriteRaw(String line)` to `SeparatedValueWriter`.

**Comment by rgarrison12345** [comment]
Yes thank you I would appreciate that.  Other file parser libraries have a
write raw string like System.XML and Newtonsoft.

**Comment by jehugaleahsa** [comment]
You should be able to write raw output as of v4.3.4. Give it a try whenever you get a chance.

**Comment by rgarrison12345** [comment]
Works great thanks for the update
