### ISSUE TITLE
RecordNumberColumn does not work when used with SeparatedValueTypeMapper 

### ISSUE THREAD

**Issue by albertoVieiraNeto** [jehugaleahsa/FlatFiles#50]
**Describe the bug**
the custom mapping RecordNumberColumn does not work when used with the class SeparatedValueTypeMapper when its created using the "DefineDynamic" function.

**To Reproduce**
```csharp

//create a dynamic mapper
var mapper = SeparatedValueTypeMapper.DefineDynamic(type);

// add some fields
mapper.Int32Property(field);

// add a custom maping
mapper.CustomMapping(new RecordNumberColumn("RecordNumber")
{
       IncludeSchema = true,
      IncludeSkippedRecords = true
})
```
**Expected behavior**
the column to be available when calling reader.Current

```csharp

//create a mapper
var selector = new SeparatedValueTypeMapperSelector();

// add some layouts
 foreach (var item in _EdiStatus.EdiImport.EdiImportRowtypes)
{
            selector.When(x => x[(int)item.EdiImport.IndexOfTypeField] == item.RecordType).Use(MapperDelimitedMapperFactory(TypeDefinitions[item.RecordType]));
}

//options/usings omited
// try to read
 var reader = selector.GetReader(stream, options);
while (reader.Read())
{
    // reader current should have a "RecordNumber" Property
     Console.WriteLine(reader.Current.ToString());
}

```
**Version:**
4.3.4

**Additional context**

**Comment by jehugaleahsa** [comment]
Sorry, trying to set across some time to look at this. In the meantime, what is the type of `reader.Current`. I assume you're selector is returning the correct type. Trying to figure out how to reproduce this in a unit test.

**Comment by jehugaleahsa** [comment]
Oh, this is simple, actually. You just need to change your example to look like this:

```csharp
// add a custom maping
mapper.CustomMapping(new RecordNumberColumn("RecordNumber")
{
       IncludeSchema = true,
      IncludeSkippedRecords = true
}).WithReader(x => x.RecordNumber);
```

You defined the column but you also need to say what to do with it during parsing... like which property to apply the record number to. Make sense?

**Comment by jehugaleahsa** [comment]
Oh, and since you're doing things dynamically, the `WithReader` will expect an `Action<object, object>`. Pretty sure you can just say something like `(dynamic thing, dynamic value) => thing.RecordNumber = value` or use reflection or whatever you need to set that value.
