### ISSUE TITLE
On Column/Record Parsing event

### ISSUE THREAD

**Issue by rgarrison12345** [jehugaleahsa/FlatFiles#51]
I would like to see an event that takes place right before a column and record is parsed.

**Comment by jehugaleahsa** [comment]
What information would I include along with the event? Would I provide information about the column about to be parsed?

**Comment by jehugaleahsa** [comment]
I am pushing out a 4.4.0 release. I am going to eventually retire the `IColumnDefinition.Preprocessor` property. I have created 4 new lambda properties called `OnParsing`, `OnParsed`, `OnFormatting` and `OnFormatted` that get called before and after parsing and formatting values.

Eventually, I might also add events on the parsers/formatters for responding to individual column events in addition to using these delegates. Right now, you can only listen to events for an entire record.
