### ISSUE TITLE
Custom format providers

### ISSUE THREAD

**Issue by andrea-rinaldi-microarea** [jehugaleahsa/FlatFiles#52]
I need to format data, specifically double numbers, with a custom format.

In my case, if the output is requested to be 7 digits, 3 decimals, a value of:
```
12.3
``` 
should be formatted as: 
```
0012300
``` 
It is like fixed point, but with no decimal separator char.

I planned to use a custom format provider, but internally the `OnFormat` methods use `ToString`, which not support custom format providers (or better, ignore them when dealing with standard type such numbers). 

If `String.Format` was used, instead, it should work.

I am open to any suggestion which helps me to get the desired result

**Comment by andrea-rinaldi-microarea** [comment]
BTW, I have aleady considered some other options, as:

- deriving my own `Column` type: as the `xxxColumn` are `sealed`, I would need to reimplement everything, when I need only the reimplement the `OnFormat` method 

- the `Column` already has a `Preprocessor` delegate: a `Postprocessor` would probably work, allowing me to remove the unneeded decimal char 

- I can treat such columns as `StringColumn` and format them my way: this is not elegant at all, and I would use it as a last resource

Any out-of-the-box suggestion, if exists, is appreciated!

**Comment by jehugaleahsa** [comment]
The number columns take an `IFormatProvider` and an output format, or both. Which column class are you using?

**Comment by andrea-rinaldi-microarea** [comment]
I am using a `DoubleColumn`. 
I didn't found an output format which do what I need. Providing a custom `IFormatProvider` doesn't help as the `.ToString()` ignores it for number formatting.
```
.AddColumn(new DoubleColumn("NetWeight") { OutputFormat = "0000.000" }, 7); // have the point in it
.AddColumn(new DoubleColumn("NetWeight") { FormatProvider = new MyFormatProvider() }, 7); // doesn't use it
```

**Comment by jehugaleahsa** [comment]
That's very strange. I pass the format provider to the ToString method. I had a similar request several weeks ago and they complained about the same issue, so I'm confused. Perhaps ToString doesn't work the way I think it does.

**Comment by andrea-rinaldi-microarea** [comment]
It looks like is an known issue of .NET, I found several discussions [like this](https://stackoverflow.com/questions/39871955/trying-to-implement-a-custom-formatter-but-icustomformatter-format-is-never-call).

**Comment by andrea-rinaldi-microarea** [comment]
It seems it is a know issue of .NET, I found several discussions [like this one](https://stackoverflow.com/questions/39871955/trying-to-implement-a-custom-formatter-but-icustomformatter-format-is-never-call).

**Comment by jehugaleahsa** [comment]
I am pushing out a 4.4.0 release. I am going to eventually retire the `IColumnDefinition.Preprocessor` property. I have created 4 new lambda properties called `OnParsing`, `OnParsed`, `OnFormatting` and `OnFormatted` that get called before and after parsing and formatting values.

I am also adding support for setting an `IFormatProvider` on the options object to override the culture settings globally rather than needing to do it on each column individually.

You'll have to let me know whether the new delegate properties give you the flexibility you need.

**Comment by andrea-rinaldi-microarea** [comment]
It worked for me:
``` C#
.AddColumn(new DoubleColumn("NetWeight") { 
     OutputFormat = "0000.000", 
     OnFormatted = (IColumnContext context, string value) => { return value.Remove(4, 1); } 
}, 7)

values.Add(12.3); // yelds 0012300
```
I believe I can easily do the reverse job while importing.

Great, many thanks!
