### ISSUE TITLE
Handel multiple null formaters in Flat File Reading

### ISSUE THREAD

**Issue by akilachamara** [jehugaleahsa/FlatFiles#61]
Hi,

I'm trying to read a flat file and do some processes. To do that I've defined a mapper. That mapper will assign the values for each property. In the document, the date will be represented with "yyMMdd" format and it can have "      " or "000000" as a null value. That mean, if the date is 6 zeros or 6 blank spaces, the output should be null. I tried to do this by defining a NullFormater. But didn't work.

So could u please let me know how can I do this. Thank you so much.

`public class Test : DocumentRecordBase
{
public string StorageOrganisation { get; set; }
public Guid? StorageOrganisationId { get; set; }
public string StorageDescription { get; set; }
public DateTime? PaymentDueDate { get; set; }
public decimal? DiscountRate { get; set; }
public int? MaximumDaysDiscount { get; set; }
public DateTime? DateStorageChargeCommences { get; set; }
public decimal? StorageChargePerBalePerDay { get; set; }
public decimal? PenaltyInterestRate { get; set; }
public DateTime? LotAvailableDate { get; set; }
public decimal? PostSaleRechargeRebate { get; set; }
public Test() : base()
{
}

    public override T GetDocumentRecord<T>()
    {
        if (typeof(T) == typeof(Test))
        {
            return this as T;
        }
        return null;
    }

    public static IFixedLengthTypeMapper<Test> GetMapper()
    {
        var mapper = FixedLengthTypeMapper.Define<Test>();
        mapper.Property(r => r.RecordType, 2);
        mapper.Property(r => r.RecordSubType, 1);

        mapper.Property(r => r.PaymentDueDate, 6)
            .ColumnName("PaymentDueDate")
            .InputFormat("yyMMdd")
            .NullFormatter(NullFormatter.ForValue("000000")); // if the read value is "000000" or "      " then should pass as null

       
        mapper.CustomMapping(new RecordNumberColumn("RecordNumber")
        {
            IncludeSchema = true,
            IncludeSkippedRecords = true
        }, 0).WithReader(r => r.RecordNumber);
        return mapper;
    }

    public static bool GetMapperPredicate(string x)
    {
        return x.StartsWith("11A");
    }

}`

Kindly note that my current method only works for "000000" and it will return null. But for the date with "      " it returns an exception saying '' cannot be converted to DateTime Column.

**Comment by jehugaleahsa** [comment]
I was looking at the implementation of `ColumnDefinition<T>` and `NullFormatter` this morning.

It looks like any trimming is done after checking for `null`s: https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles/ColumnDefinition.cs#L275

It looks like `NullFormatter.ForValue` checks for `null` and the value you pass in only, not whitespace: https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles/NullFormatter.cs#L46

I debated whether `NullFormatter.ForValue` should be checking for blank strings as well, but for now will leave the code as-is.

You can create a small implementation of `INullFormatter` for now:
```c#
public class BlankOrValueNullFormatter : INullFormatter
{
    private readonly string value;

    public BlankOrValueNullFormatted(string value)
    {
        this.value = value;
    }

    public bool IsNullValue(IColumnContext context, string value)
    {
        return String.IsNullOrWhitespace(value) || value == this.value;
    }

    public string FormatNull(IColumnContext context) => value;
}
```

Sorry if there's a syntax error - I didn't try to compile that locally.
