### ISSUE TITLE
Skipping empty rows

### ISSUE THREAD

**Issue by advapiIT** [jehugaleahsa/FlatFiles#62]
Hello,
I'm using your lib to parse input files... till today every file has no empty rows (I have a schema where each row has 512 characters).

Today a wrong file arrived, where it has 3 empty rows, each one of 0 characters. This leads to an exception telling that

> The record did not meet the length requirements specified in the schema. Record 2.

   at FlatFiles.FixedLengthReader.ProcessError(RecordProcessingException exception)
   at FlatFiles.FixedLengthReader.PartitionRecord(String record)
   at FlatFiles.FixedLengthReader.PartitionWithFilter()
   at FlatFiles.FixedLengthReader.ParsePartitions()
   at FlatFiles.FixedLengthReader.Read()
   at FlatFiles.TypeMapping.FixedLengthTypeMapper`1.<Read>d__74.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Aon.Benefit.Flussi.Services.Import.FlussoEsclusioneImportService.ReadFile(String filePath) in C:\Repos\Aon.AonBenefit\Aon.Benefit.Flussi\Services\Import\FlussoEsclusioneImportService.cs:line 39

How can I tall FlatFiles to skip empty rows?

Thanks in advance

**Comment by jehugaleahsa** [comment]
Give the README a read https://github.com/jehugaleahsa/FlatFiles/blob/master/README.md#skipping-records and let me know if you encounter any issues.

**Comment by advapiIT** [comment]
Hello,
I've read it, you use the FixedLengthReader, but currently I'm using

```
 using (var reader = new StreamReader(File.OpenRead(fullPath)))
                {
                    var mapper = FlussoEsclusioniReturnMap.GetMapper();

                    var result = mapper.Read(reader).ToList();

                    return result;
                }
```
Is there a way I can practice some ignore rule on row length?
Thanks

Paolo

**Comment by jehugaleahsa** [comment]
Not sure what that mapper is, but the `TypedReader` interfaces have the same events for skipping records as the low-level readers. For fixed length records you should be able to see if the length is less than expected and skip them.

**Comment by geekcyclist** [comment]
@advapiIT We ran into similar problems with our flat file parsing using mappers. For use we get rows with an Id and then none of the rest of the data. Below are two ways we approached it:

```csharp
var mapper = FixedLengthTypeMapper.Define<Customer>();
mapper.Property(c => c.Id, new Window(10));
mapper.Property(c => c.FirstName, new Window(20));
//... other properties
        
var reader = mapper.GetReader(stringReader);

//  Use this if you want to ignore but also track any records with errors
//  List<int> errorRecords = new List<int>();
//  reader.RecordError += (sender, e) =>
//  {
//      errorRecords.Add(e.RecordContext.PhysicalRecordNumber);
//      e.IsHandled = true;
//  };
        
//  Use this if you want to simply skip rows that are too short.
reader.RecordRead += (sender, e) => 
{ 
    e.IsSkipped = e.Record.Length < 11; 
 };
            
var customers = reader.ReadAll().ToList();
```
