### ISSUE TITLE
Add support for having multiple columns mapped to one class property

### ISSUE THREAD

**Issue by dariosoltani** [jehugaleahsa/FlatFiles#64]
I would find it quite useful when using the reader functionality to be able to mapp more than one column from a source file to one of my class properties.

Something like:
`mapper.Property(c => c.address).ColumnName("address").**AdditionalColumnName("address2")**;`

**Comment by jehugaleahsa** [comment]
If I did this, when reading, both `address` and `address2` would overwrite the `address` property... which one wins? Same with when I write out: would I write `address` or `address2` to the column?

Fortunately, if you need to combine them somehow (for instance, separating them with a space), there is custom mappers: 

```csharp
mapper.CustomMapping(new StringColumn("address")).WithReader((ctx, record, value) =>
    {
        record.Address = (string)value;
    });
mapper.CustomMapping(new StringColumn("address2")).WithReader((ctx, record, value) => 
    {
        record.Address = String.Join(" ", record.Address, (string)value);
    });
```

Admittedly, this is an advanced usage, but it should still be possible. I might have a bug up above - I didn't test that code. You might need to play around with it for a bit to get comfortable with the interface.

I have several unit tests for `CustomMapping` you can look at to try to understand how it works: https://github.com/jehugaleahsa/FlatFiles/search?q=CustomMapping&unscoped_q=CustomMapping
