### ISSUE TITLE
FlatFileException for missing matcher should bubble as RecordProcessingException 

### ISSUE THREAD

**Issue by jods4** [jehugaleahsa/FlatFiles#68]
This is a request for a slight improvement.

We are parsing a fixed-width format that starts with 2 characters indicating the type of row, i.e. the actual fields depend on the first 2 chars.
```
01First Name   Last Name
02Something totally different
03Etc etc etc
```

Of course this works perfectly fine, thanks to FlatFiles being able to choose a schema based on the data itself.

If we receive a file that starts with an unknown code, e.g. `04` in previous example, FlatFiles fails to match a schema and throws a `FlatFileException`. This seem to happen at various places in code, for example here:
https://github.com/jehugaleahsa/FlatFiles/blob/a50833ec8cdd6e8798c9fbeffb268390b638cb36/FlatFiles/FixedLengthSchemaSelector.cs#L95

The problem with this is that there is no row context, so when the outer code catches the exception it knows what's wrong but has no idea on which row.
If you receive files with 1000 lines this can be annoying.

It would be great if you could refactor the code so that this is reported as a `RecordProcessingException` so that we have access to the row context.

As `RecordProcessingException` derives from `FlatFileException` this change shouldn't break existing code.

**Comment by jehugaleahsa** [comment]
That sounds pretty straight-forward. Since that method is `internal` it might even make sense to just return `null` and have the `FixedLengthReader` throw the exception directly.

**Comment by jehugaleahsa** [comment]
I just pushed 4.11.0. If it looks good, please close the ticket.

**Comment by jods4** [comment]
Thanks!
