### ISSUE TITLE
Duplicate columns?

### ISSUE THREAD

**Issue by drmcclelland** [jehugaleahsa/FlatFiles#69]
I am using this library to import CSV data (into a DataTable) but the CSV data is duplicated column headers (similar to the following):

```
ID,Description,Date,Time,Price,Date,Time,Price
"1","Net Profit","8/3/2020","9:58:48","$111.11","8/3/2020","10:41:10","$333.33"
"2","Net Loss","8/3/2020","14:41:10","$444.44","8/3/2020","16:29:08","$222.22"

```
I would like to import this into a DataTable with the following column names:

- ID
- Description
- PurchaseDate
- PurchaseTime
- PurchasePrice
- SellDate
- SellTime
- SellPrice

Although your documentation is very good, I didn't notice an example of how to handle renaming these duplicate columns, could you give me hint?

**Comment by jehugaleahsa** [comment]
Not positive this is exactly what you were looking for, but I put together a quick unit test for you to look at: https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles.Test/DataTableExtensionsTester.cs#L460

Actually having duplicate headers in the original CSV when reading isn't required. I always use the ordinal position (the order the headers appear in the file) to retrieve data, not using the header name. In that regard, the headers are only needed if you are writing out to a file.

Shoot me back another comment if it's not exactly what you were thinking or it spurs further questions. If it looks good, please close the issue. Thank you!

**Comment by drmcclelland** [comment]
Yes, that works, thank you very much
