### ISSUE TITLE
Fixed Length Files - Decimal without decimal point separator

### ISSUE THREAD

**Issue by danilo-gomes** [jehugaleahsa/FlatFiles#73]
I am using FlatFiles to format fixed text files with decimals that must be persisted without a decimal point separator and wanted help on how I could implement using FlatFiles. Is there any way to do this today?

Example: 

Amount 152.98 (decimal)
Desired result: 00015298

**Comment by jehugaleahsa** [comment]
Short answer, yes, you can do this today.

Probably the easiest thing to do is use the `DecimalColumn` or `DoubleColumn` classes and then use the [OnFormatting](https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles/ColumnDefinition.cs#L56) event handler to multiply the number by 100.

With that, you should be able to just use the "0" placeholder [custom format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) to get the desired zero padding you need, by updating the [OutputFormat](https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles/DecimalColumn.cs#L33) property.

Something like this:
```csharp
var column = new DecimalColumn("amount");
column.OutputFormat = "0000000";
column.OnFormatting = (ctx, value) => ((decimal) value) * 100);
```

It's very similar if you're using the type mappers.

**Comment by danilo-gomes** [comment]
I really appreciate the help, I just want to take one more question. 

Is there a way for the library to automatically padding (fill zeros) considering the lenght of the field, without the need to fill the OutputFormat property explicitly with the number of zeros?

**Comment by jehugaleahsa** [comment]
If you're working with a delimited file (e.g., CSV), then no. If you are working with a fixed-width file, then yes.

When you specify the width of each fixed-length column, you are implicitly passing in a `Window` object. You can specify the `FillCharacter` at the column level or even at the writer level (using the options object): https://github.com/jehugaleahsa/FlatFiles/blob/master/FlatFiles/Window.cs#L65

It looks like this when you are creating your schema:
```csharp
schema.AddColumn(new DecimalColumn("amount"), new Window(10) { FillCharacter = '0' });
```
