### ISSUE TITLE
Write to CSV when the rows are null and tables have only schema

### ISSUE THREAD

**Issue by AlankrithaBarla** [jehugaleahsa/FlatFiles#74]
**Describe the bug**
When we try to create a Flatfile with empty array, it doesn't create the header row even though `IsFirstRecordSchema=true`.

**To Reproduce**
A console application is here : 
https://gist.github.com/AlankrithaBarla/80cdfeb026f3229038f9379cb69a0044

**Expected behavior**

```
==================== EMPTY CSV ====================
Id,Name,Weight
==================== EMPTY  CSV ====================
==================== FULL CSV ====================
Id,Name,Weight
1,Bob,185
2,Tom,210

==================== FULL  CSV ====================
```

**Actual Behavior**

```
==================== EMPTY CSV ====================

==================== EMPTY  CSV ====================
==================== FULL CSV ====================
Id,Name,Weight
1,Bob,185
2,Tom,210

==================== FULL  CSV ====================
```

**Version:**

``` FlatFiles Version="4.13.0" ```

**Comment by jehugaleahsa** [comment]
This may be a duplicate: https://github.com/jehugaleahsa/FlatFiles/issues/28. Basically you can explicitly write the header and subsequent calls won't write it a second time.

**Comment by zippy1981** [comment]
@AlankrithaBarla it looks like  instead of using `mapper.Write();` you can do:

```C#
           var schemaWriter = mapper.GetWriter(writer, options);
            schemaWriter.WriteSchema();
            schemaWriter.WriteAll(models);
            writer.Flush();
            var emptyCsv = writer.GetStringBuilder().ToString();
```

@jehugaleahsa I still think `mapper.Write()` in the example code should write the columns, althought changing the behavior would be risky for existing code. I don't mind the extra code its just the default behavior seems unintuitive. Perhaps if there was an overload on `mapper.Write()` with an "AlwaysWriteHeader" paramater, or a similar parameter in the options.

**Comment by jehugaleahsa** [comment]
@zippy1981 maybe the thing I was missing is that calls to `WriteAll` should write the header no matter what. Calling code shouldn't need to care. My previous post was specifically for someone never calling write at all, when writing one record at a time.

**Comment by jehugaleahsa** [comment]
See https://www.nuget.org/packages/FlatFiles/4.14.0. I changed the behavior of `WriteAll` to write the header/schema row. I also found some minor bugs related to reading empty files containing only a header/schema row. Please let me know if you encounter any issues. And thanks @zippy1981 for breaking down the issue the a little further.

**Comment by jehugaleahsa** [comment]
If I don't here anything after this week, I will consider this resolved. Thanks!

**Comment by zippy1981** [comment]
Hey, this works fine with mapper.GetWriteer.WriteAll(), but not with mapper.Write().

**Comment by jehugaleahsa** [comment]
Thanks for the feedback. I will just change these implementations to call `WriteAll` under the hood.
