### ISSUE TITLE
ReadAsync method missing on type mappers

### ISSUE THREAD

**Issue by silkfire** [jehugaleahsa/FlatFiles#75]
Is there a reason why the the `Write` method comes with an asynchronous version, but not the `Read` method? I'm certain that the underlying `TextReader` comes with async reading behaviour.

**Comment by jehugaleahsa** [comment]
Which class? Which interface?

**Comment by silkfire** [comment]
I'm referring to the `IFixedLengthTypeMapper` specifically as that's the interface I'm using.

**Comment by jehugaleahsa** [comment]
Oooh. Okay. Digging through the code helped wake up some brain cells.

With `Write`, you are passing me the entire list of entities to write out to the file or whatever. I can do that all in a single operation. Reading is a little different. Some people might want to read the entire collection into memory in a single operation (a.k.a., `ReadAll`), which would use a lot of memory potentially, and other people might want something C# didn't support at the time: https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8. The `awaitable foreach` could be manually simulated using a while loop back when I wrote this, even if it wasn't ideal, and you could do this using the `GetReader` and calling `ReadAsync`.

**Comment by jehugaleahsa** [comment]
Just so you know, I am looking to see how to conditionally include support for `IAsyncEnumerable` in .NET standard 2.1 and .NET Core 3.0+. It's not too bad; I'll let you know.

**Comment by silkfire** [comment]
Apologies, it was late and I realize I didn't bother wording the issue properly, hopefully it should be clearer now :)

I thought it was a bit unintuitive for the consumer to find an async `Write` method but not an equivalent async `Read `method.

I would suggest adding two methods, one to read the entire list asynchronously, perhaps with a helper `ReadToList` method (to avoid `(await mapper.Read).ToList()`), and one with `IAsyncEnumerable` support.

**Comment by jehugaleahsa** [comment]
So, there's now a 4.16.0 out there. All I did was add new methods working with `IAsyncEnumerable`.

I changed a few of the convenience methods on the mapper to reuse the extension methods on the typed reader/writer classes under the hood, since I was essentially duplicating this code.
