### ISSUE TITLE
Bug in RecordError functionality when IsHandled is set

### ISSUE THREAD

**Issue by kamatvedita99** [jehugaleahsa/FlatFiles#81]
**My business case**
I want to parse a fixed length file, and collect all parsing errors in a data structure. For FixedLengthTypeMapper, I am using the event RecordError and setting IsHandled to true. The expected behaviour is that it parses all rows and gathers all exceptions in the data structure. But it stops parsing after first erraneous record is encountered. 
**Source Code**
![image](https://user-images.githubusercontent.com/62342400/154811020-76bcd0c0-07c5-466a-b87d-fbee83381b9c.png)

![image](https://user-images.githubusercontent.com/62342400/154802780-890031dd-00ed-4b0f-95da-784c5e37cfe6.png)
**File Content**
![image](https://user-images.githubusercontent.com/62342400/154811044-02f74749-bfdc-40d6-8afb-81e2c8f3be4b.png)

**Output**
![image](https://user-images.githubusercontent.com/62342400/154811167-ea865083-efa0-4a0d-9c16-614d05741ea2.png)

**Expected Output**
Record: 123Bob17Exception: FlatFiles.RecordProcessingException: The record did not meet the length requirements specified in the schema. Record 1.
Record:  D24Jorw233Exception: FlatFiles.RecordProcessingException: Encountered an invalid conversion while processing the record. Record 2.
**Version:**
I am using FlatFiles 4.16.0 version installed via Nuget Package Manager, .NET framework - 4.7.2
**Additional context**
I have tried running this by cloning your source code, and it works absolutely fine i.e gathers all exceptions. But when installed via Nuget Package Manager it does not work. Also, as per my observation it does not work when the error is related to row length not matching schema requirements.It works as expected if the errors are column parsing errors.

**Comment by jehugaleahsa** [comment]
Sorry if it's not related, but your code sample doesn't make sense. You are building a single string containing the three data rows and then calling `String.Join` on it. You probably want:
```csharp
string[] lines = new string[] 
{
    "123Bob17",
    "D24Tomw233",
    "123Ved1714"
};
```

**Comment by kamatvedita99** [comment]
@jehugaleahsa You are right. I was actually reading from file, so it is a list of strings being read. I have modified the example. I hope it makes sense now.

**Comment by jehugaleahsa** [comment]
I decided to just move forward with my changes in master and created a 5.0.0 release: https://www.nuget.org/packages/FlatFiles/

There may be some incompatibilities with the 4.x version. Primarily, I renamed the `SeparatedValue*` classes to `Delimited*`, but there might have been a few other subtle differences.

**Comment by kamatvedita99** [comment]
Thanks Travis. This issue is resolved in 5.0.0 release.

**Comment by kamatvedita99** [comment]
If you don't mind,could you let me know what the real problem was. I am just curious to know, why it wasn't working as expected previously.

**Comment by jehugaleahsa** [comment]
The old code would see `IsHandled` set to true and just return `null`. Other code also used `null` to indicate the end of file had been reached. It was misinterpreting the `null` the wrong way and exited immediately.

**Comment by kamatvedita99** [comment]
Got you, thanks 😃
