### ISSUE TITLE
Exception "An attempt was made to retrieve the schema when none was extracted or provided."

### ISSUE THREAD

**Issue by 2226cc** [jehugaleahsa/FlatFiles#82]
Updated nuget packages and grabbed v5.0.0.
I'm now getting an exception when using FixedLengthTypeMapper with a custom mapping, and using the writer from a FixedLengthTypeMapperInjector. All working prior to v5.0.0.

The exception thrown is "An attempt was made to retrieve the schema when none was extracted or provided".

I've attached a sample solution showing the issue. It contains a single injector entry to just have the minimum amount of code, but in practice there is usually more than 1 record type class.
The custom mapping is used to provide a formatted amount in the output.

Is there are different approach that I should be taking with 5.0.0 compared to 4.16.0?

[FixedLengthTester.zip](https://github.com/jehugaleahsa/FlatFiles/files/8124081/FixedLengthTester.zip)

**Comment by jehugaleahsa** [comment]
This is a bug on my part that I introduced in v5.0.0. I found a solution tonight, but I want more time to make sure my solution is solid.  I will try to make time tomorrow night to push out my fixes.

Thank you for the tests - that really cuts down on the time it takes to diagnose and resolve issues! I was able to make 4 new unit tests that should prevent a mistake like this from happening again.

**Comment by 2226cc** [comment]
Thank you. Very much appreciate your efforts on this library.

**Comment by jehugaleahsa** [comment]
I put out a patch release v5.0.1. Please give it a try. I am not totally happy with the solution, so I will probably revisit this at a later time.

**Comment by 2226cc** [comment]
Confirmed working.
Thank you.
