### ISSUE TITLE
Setting DefaultValue on type mapper doesn't set IsNullable = false.  Alternatively, no way to set IsNullable through the type mapper interface

### ISSUE THREAD

**Issue by rkramer1964** [jehugaleahsa/FlatFiles#89]
When creating a property on a type mapper, there is a way to set the default value, but it is ignored as the IsNullable property is still true.

**Steps to Reproduce**
public class TestClass
{
   public string PropertyWithDefault { get; set; } = string.Empty;
};

var map = FixedLengthTypeMapper.Define<TestClass>();
map.Property(x => x.PropertyWithDefault, 10).DefaultValue(DefaultValue.Use("MISSING"));

var item = map.GetReader(someTextReaderWithABlankLine).Read();

// item.PropertyWithDefault is null...

**Expected behavior**
item.PropertyWithDefault should equal "MISSING"

**Version:**
5.0.2

**Additional context**
Need a way to either set IsNullable from mapping, OR assume when a default gets set through the mapping IsNullable = false

**Comment by jehugaleahsa** [comment]
I will take a look this weekend. I am curious to see if this is a bug, expected behavior, or something where the current behavior isn't intuitive (sounds like the latter).

**Comment by jehugaleahsa** [comment]
I added the ability to configure columns as nullable in the type mappers, via `Nullable(true)`. It is available in 5.0.3, so let me know if you helps you resolve your issue.

**Comment by rkramer1964** [comment]
It did.  Thank you
