### ISSUE TITLE
ExcelHelpers GetConnectionString oldExtensions typo

### ISSUE THREAD

**Issue by ufosnowcat** [jehugaleahsa/FlatFiles#9]
Hello, 
i noticed a probable typo in FlatFiles.excelHelpers.getConnectionString(string fileName)

string[] oldExtensions = new string[]
            {
                ".xsl"     -----> should be ".xls"
            };

see
https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions#Excel

For the rest tnx for the handy library :)

**Comment by jehugaleahsa** [comment]
Thanks for the bug report. I have corrected the extension and pushed out a new version to NuGet.

**Comment by ufosnowcat** [comment]
tnx
