### ISSUE TITLE
Custom Schema Templated Mapping Logic Returns Incorrect Context

### ISSUE THREAD

**Issue by moehoward003** [jehugaleahsa/FlatFiles#91]
**Describe the bug**
We are creating a templated library for Flatfiles usage. The idea being we can define columns associated with entities and have a sector for mapping the columns for writing entitles to files. When there are more than one different type of entities being written, the first entity context, values and properties all work as expected. However, for writing the second (and beyond) different entities, the context is not correct (it always uses the first entity's context). The values and properties on subsequent entities always appear to be correct as they have the same number if indexes and property members/values. The error we get when trying to write out the second entity and we get this error:

**System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'**

**To Reproduce**

This is the setup for mapping entities to a mapper:

        `selector.When((entity) => {return entity.GetType() == section.EntityType;  }).Use(GetGenericMapper(section));`

The "GetGenericMapper()" has the following logic (suspect the issue may be in this function setup?):
 
  ```
         protected IDynamicFixedLengthTypeMapper GetGenericMapper(SectionSchema section)
         {
            var mapper = FixedLengthTypeMapper.DefineDynamic(section.EntityType, () => { return Activator.CreateInstance(section.EntityType); });
            foreach (var column in section.Columns)
            {
                  mapper.CustomMapping(new FileWriterColumnDefinition(column.Name, column.Type, column.DateTimeFormat), column.Length)
                     .WithWriter((context, property, values) => {

                        var prop  = property.GetType().GetProperties()[context.LogicalIndex];
                        values[context.LogicalIndex] = prop.GetValue(property, null); //<== Context is always for the first entity
                     });
             }
            return mapper;
         }
```

The main loop as this logic:

```
           dssFileWriter.Write(header);  <== context, property and values are all correct
           dssFileWriter.Write(detail1);  <== throws exception, context from header entity is being used. (values and property are correct)
           dssFileWriter.Write(detail2);
           dssFileWriter.Write(trailer);
```

**Expected behavior**
Correct context should be provided within the anonymous function for extracting values from properties

**Screenshots**
N/A

**Version:**
5.0.3 

**Additional context**
Added demo VS 2022 solution that has all the code noted here.
Even tried to extract and assign the values like this and got the same exception:

``` 
foreach (var column in section.Columns)
{
   PropertyInfo entityProperty = section.EntityType.GetProperty(column.Name);

   mapper.CustomMapping(new FileWriterColumnDefinition(column.Name, column.Type, column.DateTimeFormat), column.Length)
   .WithWriter((context, property, values) => {
          values[context.LogicalIndex] = entityProperty.GetValue(property); //<== Same issue with context
          });
 }
```
[FlatfilesTest.zip](https://github.com/jehugaleahsa/FlatFiles/files/10086436/FlatfilesTest.zip)

**Comment by moehoward003** [comment]
Update: If I comment out this code within "FlatFiles.FixedLengthWriter", I get the expected context and all works fine. Any input on this?

```
        private IRecordContext GetMetadata()
        {
            //if (recordWriter.Metadata != null)
            //{
            //    return recordWriter.Metadata;
            //}
            var schema = recordWriter.GetSchema(new object[0]);
            var executionContext = new GenericExecutionContext(schema, recordWriter.Options.Clone());
            var recordContext = new GenericRecordContext(executionContext)
            {
                PhysicalRecordNumber = recordWriter.PhysicalRecordNumber,
                LogicalRecordNumber = recordWriter.LogicalRecordNumber
            };
            return recordContext;
        }
```

**Comment by jehugaleahsa** [comment]
Sorry. You sent this right as I was starting some time off from work but, don't worry, I've been following along. I just wanted to let you know this is on my radar. Those `GetMetadata` calls got updated as part of the 5.x upgrade, and this isn't the first time they've caused me headaches.

I will try to keep this issue on my radar until this weekend when I can actually focus on it (work has been a lot lately). The closer you can get me to an actual unit test that reproduces the issue, the faster I'll be able to knock this out. Your code above looks good for starters... do you have some test data to go with it? Is what's in the ZIP file a good example?

**Comment by moehoward003** [comment]
Appreciate the update. Yes, the zip file contains the code to repro this issue. If you run it, you'll be presented with the error in question. In the meantime, we have a work around. Thanks.

**Comment by jehugaleahsa** [comment]
I pushed version 5.0.4 to NuGet. Please let me know if it resolves your issue and, if so, please close the issue. Thanks!

**Comment by moehoward003** [comment]
Our project got cancelled and all work in this area needed to stop. But if the test app that I sent now works with this new version, all is good. Will also try it and close if so.

Thank you .

**Comment by moehoward003** [comment]
Version 5.0.4 resolved this issue. Thank you.
